### PR TITLE
The last section of the lesson is prescient - it's 2016 now, and the lesson is no longer accurate in terms of math. I've adjusted the age and year in the lesson. I don't believe I can address the error this creates in the test file at this point. 

### PR DESCRIPTION
**Pull request by walwoodr**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by Joll59** [comment]
@walwoodr 
In the Lab you are assuming the year is 2016. 
The Read Me tells you 

> If the year is currently 2016 and I was born in 1984, when I call the method current_age_for_birth_year and provide it my birth year, 1984, by passing that year as an argument, current_age_for_birth_year(1984), I expect it to return 32.

This was not an oversight, the Read Me addresses this issue towards the end.

**Comment by walwoodr** [comment]
Considering that the current year is so close to 2016, I'd suggest a more abstract example ("if the year is currently 1997 and I was born in 1984") or updating so that it's the current year. This example is distracting from the point of the lesson.

**Comment by jmburges** [comment]
@walwoodr yeah we are changing this to be a more dynamic case in general. That way this year issue won't be as much of a concern moving forward :)

**Comment by Joll59** [comment]
@walwoodr This is a fantastic idea. I will implement this and generate a pull request.

**Pull request closed without merging**
